### ISSUE TITLE
Wandboard qca, random error while loading wifi firmware

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#20]
Hi,

As mentioned in the issue #19 we've noticed a random bug that affect the wifi on the qca revision of the wandboard.

Sometime the firmware won't load and sometime ti will. Apparition of the bug seems chaotic. Below are two logs captured with minicom on the android 8 given by technexion -> https://github.com/technexion-android/cookers/tree/tn-o8.0.0_1.0.0-ga#technexion-android-8-sdk-for-imx6imx7-platforms

[minicom-d1-qca-bug1.log](https://github.com/technexion-android/cookers/files/4896893/minicom-d1-qca-bug1.log)
[minicom-d1-qca-bug2.log](https://github.com/technexion-android/cookers/files/4896895/minicom-d1-qca-bug2.log)

Despite the fact that the image do not end its boot. We can already spot the described wifi issue.

On this board we are running an android 7 which shows the same symptoms. With other version of the firmware and qcacld driver. I've tried to track the error, but I don't have any clue so far.

Thank's for your help.
Regards,
Thomas

**Comment by thomasLavocat** [comment]
As a second thought, maybe this not the same bug as in our androi7 version. Let's try to fix #19 before jumping to fast to conclusion.

**Comment by wigcheng** [comment]
It seems you're boot success, just WiFi driver initial failed (should be due to no correct firmware), but you said you cannot see anything on screen (or it's random issue, sometimes boot success?), that strange.

Did you try our demo image before? It works or not?
ftp://ftp.technexion.com/demo_software/WANDBOARD/wandboard-imx6/wandboard-android-8.0.0-20181023-sdcard/

Thanks

**Comment by thomasLavocat** [comment]
Hello,

To clarify, the issues. 

* Every time, the wifi firmware does not load.
* Every time, the boot fails and the screen is black.

## about wifi

The firmware is correctly installed. We got the zip from sales `qca9377-3_qca6174-3_firmware_20191128.zip`. And it was unziped in the right folder.
Inside the `device/fsl/wandboard/wifi-firmware/`folder I have : 

```
|-- QCA9377                            // I copied qca9377 to an uppercase folder just to be sure it was not a case issue
|   |-- CadenceLicense.txt
|   |-- Notice.txt
|   |-- bdwlan30.bin
|   |-- otp30.bin
|   |-- qwlan30.bin
|   `-- utf30.bin
|-- qca
|   |-- btfw32.tlv
|   |-- btnv32.bin
|   |-- notice.txt
|   |-- nvm_tlv_3.2.bin
|   `-- rampatch_tlv_3.2.tlv
|-- qca6174
|   |-- CadenceLicense.txt
|   |-- Notice.txt
|   |-- bdwlan30.bin
|   |-- otp30.bin
|   |-- qwlan30.bin
|   `-- utf30.bin
|-- qca9377
|   |-- CadenceLicense.txt
|   |-- Notice.txt
|   |-- bdwlan30.bin
|   |-- otp30.bin
|   |-- qwlan30.bin
|   `-- utf30.bin
|-- wlan
|   |-- cfg.dat
|   |-- qca6174
|   |   `-- qcom_cfg.ini
|   `-- qca9377
|       `-- qcom_cfg.ini
`-- wlan.ko
```

As we can see, wlan.ko is well produced upon compilation.

## about boot

If you look into the logs, there is this section :

```
581 init: init first stage started!                                                 
582 init: bool FirstStageMount::InitRequiredDevices(): partition(s) not found in /sys, waiting for their uevent(s): cache, system, userdata, vendor
583 init: Wait for partitions returned after 10.0031 seconds                        
584 init: bool FirstStageMount::InitRequiredDevices(): partition(s) not found after polling timeout: cache, system, userdata, vendor
585 init: Failed to mount required partitions early ...                             
586 init: panic: rebooting to bootloader                                            
587 init: Reboot start, reason: reboot, rebootTarget: bootloader   
```

Init tries to load system, cache, userdata and vendor partitions but fails to do so.
Then it panics and restart to bootloader.
That's why we do not see anything on screen.
I applied the procedure to flash the SD card, I used flashcard.

Here is the log of flashcard :

```
flashcard /dev/sdb
/dev/sdb start
make gpt partition for android: partition-table.img
17+0 records in
17+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00949401 s, 1.8 MB/s

/dev/sdb:
 re-reading partition table
GPT fdisk (gdisk) version 1.0.3

Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: damaged

****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
****************************************************************************

Command (? for help): 
Recovery/transformation command (? for help): Warning! This will probably do weird things if you've converted an MBR to
GPT form and haven't yet saved the GPT! Proceed? (Y/N): 
Recovery/transformation command (? for help): Warning! Secondary header is placed too early on the disk! Do you want to
correct this problem? (Y/N): Have moved second header and partition table to correct location.

Final checks complete. About to write GPT data. THIS WILL OVERWRITE EXISTING
PARTITIONS!!

Do you want to proceed? (Y/N): OK; writing new GUID partition table (GPT) to /dev/sdb.
The operation has completed successfully.
formating android images
format_partition: userdata:/dev/sdb10 ext4
mke2fs 1.44.5 (15-Dec-2018)
/dev/sdb10 contains a ext4 file system labelled 'userdata'
	last mounted on Mon Jul 13 10:37:07 2020
Creating filesystem with 1260032 4k blocks and 315120 inodes
Filesystem UUID: 069c46be-9c38-424b-9015-54eb092e2a64
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

format_partition: cache:/dev/sdb4 ext4
mke2fs 1.44.5 (15-Dec-2018)
/dev/sdb4 contains a ext4 file system labelled 'cache'
	last mounted on Mon Jul 13 10:36:54 2020
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: b56149ff-cfe9-4206-8163-20a14f76e993
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

erase_partition: presistdata : /dev/sdb8 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.118729 s, 8.8 MB/s
erase_partition: fbmisc : /dev/sdb11 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.118275 s, 8.9 MB/s
erase_partition: misc : /dev/sdb5 4M
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.484019 s, 8.7 MB/s

/dev/sdb:
 re-reading partition table
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
WARNING: Not enough clusters for a 32 bit FAT!
== download the environment - Display: hdmi ==
== download the ramdisk ==
Image Name:   Android Root Filesystem
Created:      Mon Jul 13 10:45:22 2020
Image Type:   ARM Linux RAMDisk Image (uncompressed)
Data Size:    2038582 Bytes = 1990.80 KiB = 1.94 MiB
Load Address: 10800800
Entry Point:  10800800
== download the system ==
1536+0 records in
1536+0 records out
1610612736 bytes (1.6 GB, 1.5 GiB) copied, 0.468467 s, 3.4 GB/s
== download the vendor ==
112+0 records in
112+0 records out
117440512 bytes (117 MB, 112 MiB) copied, 0.0352745 s, 3.3 GB/s
== download the recovery ==
14+1 records in
14+1 records out
15357228 bytes (15 MB, 15 MiB) copied, 0.00695619 s, 2.2 GB/s
== Erase the environment variables ==
1023+0 records in
1023+0 records out
1047552 bytes (1.0 MB, 1023 KiB) copied, 1.96244 s, 534 kB/s
3+0 records in
3+0 records out
3145728 bytes (3.1 MB, 3.0 MiB) copied, 0.348943 s, 9.0 MB/s
== flash the SPL ==
51+0 records in
51+0 records out
52224 bytes (52 kB, 51 KiB) copied, 0.0991777 s, 527 kB/s
== download the audio setting for hdmi ==
umount: /dev/sdb: not mounted.
umount: /dev/sdb10: not mounted.
umount: /dev/sdb11: not mounted.
umount: /dev/sdb2: not mounted.
umount: /dev/sdb3: not mounted.
umount: /dev/sdb4: not mounted.
umount: /dev/sdb5: not mounted.
umount: /dev/sdb6: not mounted.
umount: /dev/sdb7: not mounted.
umount: /dev/sdb8: not mounted.
Flash Done!!!
```


How can I fix this ?

## using `ftp://ftp.technexion.com/demo_software/WANDBOARD/wandboard-imx6/wandboard-android-8.0.0-20181023-sdcard/` 

There is the same boot bug with this image :

[minicom-d1-qca-bug_img_wandboard.log](https://github.com/technexion-android/cookers/files/4911225/minicom-d1-qca-bug_img_wandboard.log)

It fails to find the right partitions and then reboot to bootloader.

Thanks you for your help

**Comment by wigcheng** [comment]
Thanks for your detail description! I apologized let you spent time to verify our source code and demo image.
It really doesn't works after I download it, same error message as you post.

Actually I focus on this github project maintenance since Android 9, so I recommend adapt Android 9 if possible as following reasons:

- Support OTA
- More stable
- Fast compile time (Android 8: 1.5hr -> Android 9: 40 mins)
- Long Term Support

I know you have one question:

> I didn't see Android 9 supports WandBoard

Don't worry, I provide a **hacking patch** for you :)

You can refer https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.2.0-ga

Adapt "LTS branch (stable)" option and source the EDM1-IMX6 board 
(search For EDM-IMX6Q with FAIRY: HDMI or EDM-IMX6DL with FAIRY: HDMI, up to your CPU board)

And use this patch: 
ftp://ftp.technexion.com/demo_software/WANDBOARD/wandboard-imx6/android-9.0.0-2.2.0_wandboard-hack.patch
modify <source>/vendor/nxp-opensource/kernel_imx/arch/arm/boot/dts/imx6qdl-edm-qca.dtsi


Then recompiled, it should be boot success ( I just tested and it works).

In addition, WiFi and Bluetooth firmware need put on different path as [instruction](https://github.com/technexion-android/cookers/tree/tn-p9.0.0_2.2.0-ga#enabling-wifibt-function)

That's it, welcome to continue discuss with me if you have any problems.

BTW, if you still want to use Android 8, I need take some effort on it because it's totally different structure, I don't want to modify it cause some side impact, hope you understand.

Thanks a lot

**Comment by thomasLavocat** [comment]
Hi,

Thank you for your response. I understand why you don't want to update android 8 version. My goal is only to have a bootable image, as up to date as much as possible running on my wandboard_qca.

I did the manipulations you ask. And I still have an issue to boot.

**Minicom output :**

```
U-Boot SPL 2018.03-ga5a39ee (Jul 15 2020 - 10:32:57 +0000)
Trying to boot from MMC1


U-Boot 2018.03-ga5a39ee (Jul 15 2020 - 10:32:57 +0000)

CPU:   Freescale i.MX6Q rev1.3 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 33C
Reset cause: POR
SOM: imx6q-edm1
Available EDM1 baseboard: Fairy, Gnome, TC0700 
I2C:   ready
DRAM:  2 GiB
PMIC:  PFUZE100 ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
auto-detected panel HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
SOM: imx6q-edm1
Available EDM1 baseboard: Fairy, Gnome, TC0700 
flash target is MMC:0
Net:   FEC [PRIME]
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0 
RNG instantiation done (3600)
avb_slot_verify.c:388: ERROR: boot: Hash of data does not match digest in descriptor.
 verify FAIL, state: LOCK
```

## Using flashcard

```
flashcard /dev/sdb
/dev/sdb start
'/home/tlavocat/development/technexion/device/fsl/common/tools/gpt_partition_move' -> '/home/tlavocat/development/technexion/out/target/product/edm1_imx6/gpt_partition_move'
make gpt partition for android: partition-table-7GB.img
17+0 records in
17+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00607535 s, 2.9 MB/s

/dev/sdb:
 re-reading partition table
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

formating android images
format_partition: userdata:/dev/sdb11 ext4
mke2fs 1.44.5 (15-Dec-2018)
Creating filesystem with 1184768 4k blocks and 296592 inodes
Filesystem UUID: 27b3543f-c251-4dd6-99a2-fe11614354c2
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

format_partition: cache:/dev/sdb5 ext4
mke2fs 1.44.5 (15-Dec-2018)
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: d8c85aa4-2941-4820-933b-3fe552a560d1
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

erase_partition: presistdata : /dev/sdb9 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.000810369 s, 1.3 GB/s
erase_partition: fbmisc : /dev/sdb12 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.116647 s, 9.0 MB/s
erase_partition: misc : /dev/sdb6 4M
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.485063 s, 8.6 MB/s
flash_partition: dtbo-imx6q.img ---> /dev/sdb1
0+1 records in
0+1 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.619689 s, 6.8 MB/s
flash_partition: boot.img ---> /dev/sdb2
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 0.0336452 s, 1.5 GB/s
flash_partition: recovery-imx6q.img ---> /dev/sdb3
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 0.0290031 s, 1.7 GB/s
flash_partition: system.img ---> /dev/sdb4
flash_partition: vendor.img ---> /dev/sdb10
flash_partition: vbmeta-imx6q.img ---> /dev/sdb13
0+1 records in
0+1 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.0059247 s, 691 kB/s
erase_partition: uboot : /dev/sdb
flash_partition: u-boot-imx6q.imx ---> /dev/sdb

>>>>>>>>>>>>>> Flashing successfully completed <<<<<<<<<<<<<<
43+0 records in
43+0 records out
44032 bytes (44 kB, 43 KiB) copied, 9.0608e-05 s, 486 MB/s
flash_partition: u-boot-edm-imx6_android_spl_defconfig.img ---> /dev/sdb
1008+1 records in
1008+1 records out
516104 bytes (516 kB, 504 KiB) copied, 5.94806 s, 86.8 kB/s
Flash Done!!!
```

## Using the mass production method :

```
gen_mp_images 
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/boot.img' -> 'auto_test/boot.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/dtbo-imx6dl.img' -> 'auto_test/dtbo-imx6dl.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/dtbo-imx6q.img' -> 'auto_test/dtbo-imx6q.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table-14GB.img' -> 'auto_test/partition-table-14GB.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table-28GB.img' -> 'auto_test/partition-table-28GB.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table-3GB.img' -> 'auto_test/partition-table-3GB.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table-7GB.img' -> 'auto_test/partition-table-7GB.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table-default.img' -> 'auto_test/partition-table-default.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/partition-table.img' -> 'auto_test/partition-table.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/vbmeta-imx6dl.img' -> 'auto_test/vbmeta-imx6dl.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/vbmeta-imx6q.img' -> 'auto_test/vbmeta-imx6q.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/vendor.img' -> 'auto_test/vendor.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/system.img' -> 'auto_test/system.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/recovery-imx6dl.img' -> 'auto_test/recovery-imx6dl.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/recovery-imx6q.img' -> 'auto_test/recovery-imx6q.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/recovery.img' -> 'auto_test/recovery.img'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/u-boot-edm-imx6_android_spl_defconfig.SPL' -> 'auto_test/u-boot-edm-imx6_android_spl_defconfig.SPL'
'/home/tlavocat/development/technexion/out/target/product/edm1_imx6/u-boot-edm-imx6_android_spl_defconfig.img' -> 'auto_test/u-boot-edm-imx6_android_spl_defconfig.img'
'device/fsl/common/tools/gpt_partition_move' -> 'auto_test/gpt_partition_move'
'device/fsl/common/tools/fsl-sdcard-partition.sh' -> 'auto_test/fsl-sdcard-partition.sh'
'device/fsl/common/tools/fsl-sdcard-partition-virtual-image.sh' -> 'auto_test/fsl-sdcard-partition-virtual-image.sh'

cd auto_test/

sudo ./fsl-sdcard-partition.sh -f imx6q -c 14 /dev/sdb
make gpt partition for android: partition-table-14GB.img
17+0 records in
17+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00712854 s, 2.4 MB/s

/dev/sdb:
 re-reading partition table
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

formating android images
format_partition: userdata:/dev/sdb11 ext4
mke2fs 1.44.5 (15-Dec-2018)
/dev/sdb11 contains a ext4 file system labelled 'userdata'
	created on Wed Jul 15 14:02:16 2020
Creating filesystem with 3019776 4k blocks and 755904 inodes
Filesystem UUID: 64f656d9-cbae-4913-8764-20544738e7cf
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

format_partition: cache:/dev/sdb5 ext4
mke2fs 1.44.5 (15-Dec-2018)
/dev/sdb5 contains a ext4 file system labelled 'cache'
	created on Wed Jul 15 14:02:25 2020
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: 9b418869-9230-4beb-b5a3-7cbe37ca98a3
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

erase_partition: presistdata : /dev/sdb9 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00100368 s, 1.0 GB/s
erase_partition: fbmisc : /dev/sdb12 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.124983 s, 8.4 MB/s
erase_partition: misc : /dev/sdb6 4M
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.623747 s, 6.7 MB/s
flash_partition: dtbo-imx6q.img ---> /dev/sdb1
0+1 records in
0+1 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.513322 s, 8.2 MB/s
flash_partition: boot.img ---> /dev/sdb2
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 0.0329681 s, 1.5 GB/s
flash_partition: recovery-imx6q.img ---> /dev/sdb3
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 0.0331389 s, 1.5 GB/s
flash_partition: system.img ---> /dev/sdb4
flash_partition: vendor.img ---> /dev/sdb10
flash_partition: vbmeta-imx6q.img ---> /dev/sdb13
0+1 records in
0+1 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.0152697 s, 268 kB/s
erase_partition: uboot : /dev/sdb
flash_partition: u-boot-imx6q.imx ---> /dev/sdb

>>>>>>>>>>>>>> Flashing successfully completed <<<<<<<<<<<<<<

sudo ./gpt_partition_move -d /dev/sdb -s 4096

sudo dd if=u-boot-edm-imx6_android_spl_defconfig.SPL of=/dev/sdb bs=1k seek=1 conv=sync
43+0 records in
43+0 records out
44032 bytes (44 kB, 43 KiB) copied, 0.000142027 s, 310 MB/s

sudo dd if=u-boot-edm-imx6_android_spl_defconfig.img of=/dev/sdb bs=512 seek=92 oflag=dsync
1008+1 records in
1008+1 records out
516104 bytes (516 kB, 504 KiB) copied, 6.85755 s, 75.3 kB/s
```

**Comment by thomasLavocat** [comment]
I put here an update on the issue. I have tried to disable android verified boot with what i've found in this website : https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)

The command used is :
`~/development/technexion/./out/host/linux-x86/bin/avbtool make_vbmeta_image --flags 2 --padding_size 4096 --output vbmeta-imx6q.img`

The boot sequence then changes :

```
U-Boot SPL 2018.03-ga5a39ee (Jul 16 2020 - 07:25:39 +0000)
Trying to boot from MMC1


U-Boot 2018.03-ga5a39ee (Jul 16 2020 - 07:25:39 +0000)

CPU:   Freescale i.MX6Q rev1.3 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 38C
Reset cause: POR
SOM: imx6q-edm1
Available EDM1 baseboard: Fairy, Gnome, TC0700 
I2C:   ready
DRAM:  2 GiB
PMIC:  PFUZE100 ID=0x10
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
auto-detected panel HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
SOM: imx6q-edm1
Available EDM1 baseboard: Fairy, Gnome, TC0700 
flash target is MMC:0
Net:   FEC [PRIME]
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0 
RNG instantiation done (3600)
avb_slot_verify.c:692: ERROR: vbmeta: Error verifying vbmeta image: OK_NOT_SIGNED
 verify FAIL, state: LOCK

```

Why does the bootloader fail ?

**Comment by wigcheng** [comment]
Don't disable AVB configuration, it's an important feature in Android 9 with security.
That strange because I have no problem here ( I use Dual-Lite Sku.)

Let me clear up your steps:

1. Source EDM1 with HDMI configuration from cookers
2. Issue cook command and start compiling
3. Compile success if no any error messages
4. flashcard /dev/sdx 3 (I don't know what capacity for your uSD card, 3 means for 4GB, 7 means for 8GB, default is for 8GB)
5. after flashed, take this uSD to Wandboard and boot up and failed.

Do you use those steps as above?
Do you modify any part from source code?

Thanks, I'll try later if I find a Quad Sku. CPU module.

**Comment by thomasLavocat** [comment]
Hello.

Indeed, there is many differences between Quad and Dual Lite. I think the patch you provided for the DTS may need some adjustments to work with the Quad. Can you get one (https://www.wandboard.org/products/wandboard/WB-IMX6Q-9377/) to test please ?

I did the steps you mentioned and I have the error.
I did not change the source code.

When I decided to deactivate AVB with the magic flag, it was because I thought the error came from there. I issue the command after compilation. I did not alter the build process. So if I build again, AVB will be reactivated.

Thanks

**Comment by wigcheng** [comment]
Looking for that board, please wait a minutes...

AVB failed usually happen on force flash partial image or GPT partition table had already broken.
Could you plug-in uSD card and issue "lsblk" command on your host PC?
If the partition table still alive, you should see all partitions list, try this first.

Thanks a lot

**Comment by thomasLavocat** [comment]
No worry, I will wait.

This is the result of  `lsblk` :
```
sdb       8:16   1  14.9G  0 disk 
├─sdb1    8:17   1     4M  0 part 
├─sdb2    8:18   1    48M  0 part 
├─sdb3    8:19   1    48M  0 part 
├─sdb4    8:20   1   1.8G  0 part 
├─sdb5    8:21   1   512M  0 part 
├─sdb6    8:22   1     4M  0 part 
├─sdb7    8:23   1     2M  0 part 
├─sdb8    8:24   1     2M  0 part 
├─sdb9    8:25   1     1M  0 part 
├─sdb10   8:26   1   112M  0 part 
├─sdb11   8:27   1   4.5G  0 part 
├─sdb12   8:28   1     1M  0 part 
└─sdb13   8:29   1     1M  0 part 
```

Thanks for your prompt response.

**Comment by wigcheng** [comment]
I can boot up success using Quad core CPU module.
I need check with you about which branch you choose for "repo init", I saw we're different hash code on u-boot, that is the root cause I think.

**Comment by wigcheng** [comment]
Another concern:

Let you see my flash log, I think some image file should be flash failed on your host PC because the flash speed is too high, maybe reboot your PC or change uSD card.

$ flashcard /dev/sdd 
/dev/sdd start
[sudo] password for wig: 
'/home/wig/disk2/android/2.2.0-tn-2.0-wip/device/fsl/common/tools/gpt_partition_move' -> '/home/wig/disk2/android/2.2.0-tn-2.0-wip/out/target/product/edm1_imx6/gpt_partition_move'
make gpt partition for android: partition-table-7GB.img
17+0 records in
17+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.0472387 s, 369 kB/s

/dev/sdd:
 re-reading partition table
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.

Warning! One or more CRCs don't match. You should repair the disk!

formating android images
format_partition: userdata:/dev/sdd11 ext4
mke2fs 1.44.1 (24-Mar-2018)
/dev/sdd11 contains a ext4 file system labelled 'userdata'
	last mounted on /data on Thu Jan  1 08:00:09 1970
Creating filesystem with 1184768 4k blocks and 296592 inodes
Filesystem UUID: 3bfb885b-07cc-4d0c-bd16-94196381e471
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

format_partition: cache:/dev/sdd5 ext4
mke2fs 1.44.1 (24-Mar-2018)
/dev/sdd5 contains a ext4 file system labelled 'cache'
	last mounted on Thu Jan  1 08:00:09 1970
Creating filesystem with 131072 4k blocks and 32768 inodes
Filesystem UUID: 438886ad-1c49-4231-bc4d-9f949678cf73
Superblock backups stored on blocks: 
	32768, 98304

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

erase_partition: presistdata : /dev/sdd9 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.239486 s, 4.4 MB/s
erase_partition: fbmisc : /dev/sdd12 1M
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.352404 s, 3.0 MB/s
erase_partition: misc : /dev/sdd6 4M
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.452233 s, 9.3 MB/s
flash_partition: dtbo-imx6q.img ---> /dev/sdd1
0+1 records in
0+1 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.378445 s, 11.1 MB/s
flash_partition: boot.img ---> /dev/sdd2
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 5.5526 s, 9.1 MB/s
flash_partition: recovery-imx6q.img ---> /dev/sdd3
4+1 records in
4+1 records out
50331648 bytes (50 MB, 48 MiB) copied, 6.70861 s, 7.5 MB/s
flash_partition: system.img ---> /dev/sdd4
flash_partition: vendor.img ---> /dev/sdd10
flash_partition: vbmeta-imx6q.img ---> /dev/sdd13
0+1 records in
0+1 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.0500841 s, 81.8 kB/s
erase_partition: uboot : /dev/sdd
flash_partition: u-boot-imx6q.imx ---> /dev/sdd

 Flashing successfully completed <<<<<<<<<<<<<<
43+0 records in
43+0 records out
44032 bytes (44 kB, 43 KiB) copied, 0.000496344 s, 88.7 MB/s
flash_partition: u-boot-edm-imx6_android_spl_defconfig.img ---> /dev/sdd
1009+1 records in
1009+1 records out
516696 bytes (517 kB, 505 KiB) copied, 2.87976 s, 179 kB/s
Flash Done!!!

**Comment by wigcheng** [comment]
> I can boot up success using Quad core CPU module.
> I need check with you about which branch you choose for "repo init", I saw we're different hash code on u-boot, that is the root cause I think.

I change the same hash log as you use, it still boot up success, so not this problem, thanks.

**Comment by thomasLavocat** [comment]
Yes, you were right about the flashing speed. Rebooting my computer solved the issue.
Android 9 now boot and I have access to the interface. Thanks a lot.

I can close this issue.
