### ISSUE TITLE
Android 9, activate wifi direct.

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#21]
Hello,

The chip pixi9377 is wifi direct capable.
I'm looking for a way to activate the functionality on the demo image.
I've added the property `gEnableP2pListenOffload=1` to device/fsl/imx6dq/edm1_imx6/wifi-firmware/QCA9377/wlan/qcom_cfg.ini without success.

Any idea on how to activate it ?

**Comment by wigcheng** [comment]
Try to add one line in init.rc as following:
     # Prepare for wifi
     setprop wifi.interface wlan0
     **setprop wifi.direct.interface p2p0**

Then rebuild again, thanks

**Comment by thomasLavocat** [comment]
I've added the propriety, it does not change the behavior in the android interface.
Do you need some logs ?

```
@@ -76,6 +75,7 @@ on early-boot
     # Prepare for wifi
     setprop wifi.interface wlan0
     setprop wifi.ap.interface wlan0
+    setprop wifi.direct.interface p2p0
```

**Comment by wigcheng** [comment]
Did your WiFi Direct setting page showing any interface name such as "Android_8a68" ???

Yes, provide some log please.

**Comment by thomasLavocat** [comment]
No, the page is not showing a name such as the one you point.

Here are [logcat](https://github.com/technexion-android/cookers/files/5068223/logcat_wifidirect_issue.log) and [dmesg](https://github.com/technexion-android/cookers/files/5068226/dmesg_wifidirect_issue.log).

Thanks

**Comment by thomasLavocat** [comment]
I made a mistake with the propriety name. I have corrected the property name and it still does not work.
WiFi Direct setting page is not showing any interface name such as "Android_8a68".

Here are the logs :
[dmesg_wifidirect_issue.log](https://github.com/technexion-android/cookers/files/5068440/dmesg_wifidirect_issue.log)
[logcat_wifidirect_issue.log](https://github.com/technexion-android/cookers/files/5068441/logcat_wifidirect_issue.log)

For information, the property is well set : 

```
edm1_imx6:/ # getprop wifi.direct.interface
p2p0
edm1_imx6:/ # ndc interface list
110 0 can0
110 0 can1
110 0 eth0
110 0 ip6_vti0
110 0 ip6tnl0
110 0 ip_vti0
110 0 lo
110 0 p2p0
110 0 sit0
110 0 wlan0
200 0 Interface list completed
```

**Comment by wigcheng** [comment]
I think the root cause is NXP has not implement P2P HIDL layer as following log:
08-14 05:43:46.954   788   788 D WifiP2pSettings: NO dashboard tiles for WifiP2pSettings
08-14 05:43:46.996   355   468 D WifiP2pNative: Setup P2P interface
08-14 05:43:46.996   355   468 E HalDevMgr: getAllChipInfo: called but mWifi is null!?
08-14 05:43:46.996   355   468 W HalDevMgr: stopWifi called but mWifi is null!?
08-14 05:43:46.996   355   468 E WifiP2pNative: Failed to create P2p iface in HalDeviceManager
08-14 05:43:46.996   355   468 E WifiP2pService: Failed to setup interface for P2P
08-14 05:43:58.265   355   417 D WificondControl: Scan result ready event
08-14 05:44:38.279   355   723 D WificondControl: Scan result ready event

It need takes some effort to trace, maybe naming issue or really no support WiFi direct on Android 9 (I think it's this one).


I just tested Android 10 and it works fine, NXP was be implement P2P HAL layer, but Android 10 only support IMX8 series, sorry for cause your inconvenience, it could be don't work at this moment.

If you really need this function, please send mail to sales@technexion.com and discuss your requirement, thanks.

**Comment by wigcheng** [comment]
NXP just response me about this issue, they really don't port P2P HAL layer on Android 9.
It means it's a big task if you need, thanks.

**Comment by wigcheng** [comment]
I ported WiFi P2P HAL layer already, please issue 'repo sync' for source code upgrading and try again :smile:

**Comment by thomasLavocat** [comment]
Thanks, I will test it this morning.

**Comment by thomasLavocat** [comment]
It works. Thanks a lot.

**Comment by wigcheng** [comment]
Thanks for your feedback, please also feedback to our sales if possible.
