### ISSUE TITLE
QCA Firmware versions for wandboard

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#22]
Hello,

To build the android 9, I asked sales to send the firmware files. I received them, and they work fine. But I would like to know for which version of the qcacld driver they are for ?

And, have you other versions of this firmware available ?

The reason why I'm asking that is because, I'm running android 7. And for the qcacld driver parts, I'm using boundary devices drivers : https://github.com/boundarydevices/qcacld-2.0. It works for the most part, but, because I'm also using their firmware (https://github.com/boundarydevices/qca-firmware) , some of the files are not compatible with the wifi chip.

So I would like to have a version of the firmware that is compatible with the driver qcacld in this version : https://github.com/boundarydevices/qcacld-2.0/tree/boundary-LNX.LEH.4.2.2.2

Have you such firmware available ?
Thanks for your help

**Comment by wigcheng** [comment]
I don't understand your question, you want to have a firmware version can support our qcacld driver and boundarydevices's qcacld driver using Wandboard, becase you adapt boundarydevices's qcacld driver on our Android 7, right???

**Comment by thomasLavocat** [comment]
Hello,

Indeed my question was badly formulated, I will clarify.

**First some context :** For now, the only official android you give that support the pixi9377 on the wandboard is the android 9. But our product runs on android 7. So we had to improvise something to port the code and to make it work. What we did, was to get the driver from boundary devices. We took the driver from boundary devices because the driver you have for android 9 wont compile on android 7, the kernel versions are not compatible.

**What we have now :** The issue is that, we only have a semi functional wifi chip. And I think, this is because we do not use the firmware you provide. The reason why we do not use the firmware you provide is because, correct me if I'm wrong, for each version of a driver there is a associated firmware. And because we don't use your driver because it won't compile with android 7, we are forced to use the boundary devices firmware. And this seems wrong.

**What I would like to know :** 

- When I dig into your android 9 image, I can see that the qcacld driver code is embeded in the linux kernel code and I cannot find from which commit in code aurora it came from (https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-2.0/). Can you give me the reference commit please ?
- When I compare your firmware[1] and boundary devices firmware[2] I can see many differences in the archive structure, which led me to think that your firmware cannot be used with my current driver. Am I wrong ?
- Can you provide me a description for each file in your firmware[1] please ?
- Do you have a firmware and driver that would target android 7 ?

Thanks for your answers.


[1]
```
├── qca
│   ├── btfw32.tlv
│   ├── btnv32.bin
│   ├── notice.txt
│   ├── nvm_tlv_3.2.bin
│   └── rampatch_tlv_3.2.tlv
├── qca9377
│   ├── bdwlan30.bin
│   ├── CadenceLicense.txt
│   ├── Notice.txt
│   ├── otp30.bin
│   ├── qwlan30.bin
│   └── utf30.bin
└── wlan
    ├── cfg.dat
    └── qca9377
        └── qcom_cfg.ini
```

[2]
```
├── otp30.bin
├── qca
│   ├── tfbtfw11.tlv
│   └── tfbtnv11.bin
├── qwlan30.bin
└── wlan
    ├── cfg.dat
    └── qcom_cfg.ini
```

**Comment by wigcheng** [comment]
Understood...

I separate two parts to answer you:

1. Specific commit hash for qcacld driver of Android 9
In Android 9, WiFi driver was migrated inside the kernel source, although you cannot look for the same commit hash with qcacld driver, but you still can find the driver revision in log messages using git command as follows (and you'll see NXP tweak something):
`$ cd vendor/nxp-opensource/kernel_imx`
`$ git log drivers/net/wireless/qcacld-2.0/`

2. We adapt qcacld since Android 8, no support Android 7, but as my understand, you can running qca9377 on Android 7 using BD's driver and firmware, right? I think you can maintain it. And it's belong to custom service if you want to have a qca9377 driver for Android 7, please contact our sales window.

In addition, I think different structure in zip file is no problem, they still need place to the right path manually, and I believe they're the same no matter ours or BD's.


Thanks a lot

**Comment by wigcheng** [comment]
Let me know if you still have question, or I'll close this comment later, thanks

**Comment by thomasLavocat** [comment]
No it's okay, we will see if we ask your sales team. Thank's for your answer.
