### ISSUE TITLE
Android 9, edm1 imx6 quad (wandboard), WebView slow video playing

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#23]
Hello,

We are testing the video playback on your android 9 on a wandboard imx6 quad version. Unfortunately the displayed frame rate of the video is very low.

To perform my tests I have a local apache2 server serving a static html 5 page with the following code.

```
<html>
	<body>
		<video width="100%" controls>
			<source src="1080_3_30_reference.mp4" type="video/mp4">
		</video>
	</body>
</html>
```

You can find the reference test video here https://gopro.com/v/PovvyyJVQ6qkO It is a 1080p 3MB/s h264 video encoded at 30 frames per second.

Using cactus player and video player the video is not janky.

Can you take a look on what is happening on the webview please ?
Thank's for your help.

**Comment by wigcheng** [comment]
Tested same here, but could you check this webview is better or not:
webview:
https://www.youtube.com/watch?v=D1TeDgH5O74

local video player:
https://www.youtube.com/watch?v=kHLw1Ql33wU

Due to IMX6 limitation, the only way is increase CMA and galcore size such as following command on u-boot prompt:
setenv bootargs console=ttymxc0,115200 init=/init video=mxcfb0:dev=hdmi,1280x720M@60,if=RGB24 video=mxcfb1:off vmalloc=128M androidboot.console=ttymxc0 consoleblank=0 androidboot.hardware=freescale cma=512M galcore.contiguousSize=134217728 loop.max_part=7 quiet

That is for video one setting (CMA=512MB, galcore size=128MB), but I think you should be still feel a bit slow...


Webview browser has some limitation for HW acceleration although it does support GPU, and NXP seems no any improvement since Android 4, I have other customers face this challenge before, they usually have some workarounds:

1. reduce the video resolution to 720P (actually if your default resolution is 720P, it's okay)
2. web server send a request about shell command to playback video using local player when click play video button
3. change browser such as firefox or chromium, but I remember just improve a little bit performance.

You can try to increase CMA size to 512MB and try again.

Thanks

**Comment by thomasLavocat** [comment]
Hello,

Thanks for your answer. We will investigate whether we can use a 720p resolution or not.
In the meantime, I just realize that the default resolution of the build is on 720p and not 1080p why is that ?

How can I get the 1080p resolution by default on the android 9 build ?

Thanks.

**Comment by wigcheng** [comment]
You'll know why default resolution is 720P when you changed (not smoothly...):

1. quick way in u-boot prompt (for test):
setenv bootargs console=ttymxc0,115200 init=/init video=mxcfb0:dev=hdmi,**1920x1080**M@60,if=RGB24 video=mxcfb1:off vmalloc=128M androidboot.console=ttymxc0 consoleblank=0 androidboot.hardware=freescale cma=512M galcore.contiguousSize=134217728 loop.max_part=7 quiet



2. modify the source code in BoardConfig.mk
Modify KERNEL_CMDLINE from video=mxcfb0:dev=hdmi,1280x720M@60 to video=mxcfb0:dev=hdmi,1920x1080M@60

Thanks!

**Comment by thomasLavocat** [comment]
ok, thanks for the answer, I close the issue.
