### ISSUE TITLE
How to differenciate wandboard imx6q and wandboard imx6qp in early u-boot stage to differenciate dtb file to load

### ISSUE THREAD

**Issue by thomasLavocat** [technexion-android/cookers#27]
Hello,

I think the title is quite self explanatory ^_^
Indeed, I need to discriminate the wandboard quad from the quad plus revision to inform u-boot on which device tree binary to pickup.
In the past we used a hack where for the c1 revision we use to check a specific GPIO pin and we use to check if the c1 was using a pmic.
Is there an easy-to-use difference between the revision d1a1 and the d1a2, like a GPIO to request ?

Thanks for your answer,
Thomas

**Comment by wigcheng** [comment]
I need check it first because it's not belong to Android part, All revision don't support imx6qp platform no matter Android 8 to 10, do you trying to add imx6qp by yourselves???

But In android, you can force assign a specific dtb file in dtbo.img or boot.img (depend your android revision), u-boot no need to load correct dtb automatically, unless you're use linux OS.

Thanks

**Comment by wigcheng** [comment]
Any update?

**Comment by thomasLavocat** [comment]
Hello,

Yes I want to be able to use an wandboard imx6QP on android 7. Therefore I'm looking to update u-boot to a newer version. Because the one I use does not support QP versions yet.

Do you have a version of u-boot that is compatible with android 7 and QP ?

Thanks

**Comment by wigcheng** [comment]
I have no touch EDM-IMX6QP since I start maintain Android github (from Android 9).
Just checked earlier release, Android 8's uboot (v2017.03) should be works for you:
https://github.com/technexion-android/uboot-imx/tree/tn-o8.0.0_1.0.0-ga

Although Android 9's u-boot does support EDM-IMX6QP  in Linux OS, but that's totally different boot up flow, so I recommend you can use  Android 8's uboot first, how do you think?

**Comment by thomasLavocat** [comment]
Ok, I'll have a look and I'll keep you posted.
Thanks
