### ISSUE TITLE
Repo init error

### ISSUE THREAD

**Issue by ChatchaiBuekban** [technexion-android/cookers#28]
repo init -u https://github.com/technexion-android/manifest -b tn-p9.0.0_2.0.1_8m-ga
  File "/home/..../ASOP/.repo/repo/main.py", line 79
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

How to fix this.

**Comment by wigcheng** [comment]
What's your Ubuntu revision on host PC?
Google upgrade repo requirement using python 3.7+ since 2020 Q4, if your host PC is adapt Ubuntu 20.04, should be no problems, but if adapt 16.04 or 18.04, you need upgrade your default python revision first.

You can refer dockerfile of cookers, detail as follows commit:
https://github.com/technexion-android/cookers/commit/220082a212ecd162ea6ae1e25e9aef391d5c1534

Thanks!

**Comment by ChatchaiBuekban** [comment]
Thank for your reply, 
I have solved,  default my python is version 2.x  and worked when I set default to version 3.x or run with $ python3 repo init ...
